config/routes.rb
Rails.application.routes.draw do

  root "categories#index"

  resources :activities

  resources :password_resets

  resources :pages, only: [:show]

  resources :user_sessions

  resources :users do
    resources :requests
  end

  resources :experiences

  resources :ratings

  resources :requests do
    resources :conversations do
      resources :messages
    end
    resources :responses
  end

  resources :responses do
    resources :requests
  end

  resources :categories do
    resources :requests
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  # Tracking for Notifications (defaults to create, update, destroy)
  include PublicActivity::Common
  # tracked owner: ->(controller, model) { controller && controller.current_user }

  # ActiveRecord Relationships
  belongs_to :request
  belongs_to :user, :foreign_key => :sender_id
  belongs_to :user, :foreign_key => :recipient_id
  has_many :messages, dependent: :destroy

  # ActiveRecord Validations
  validates :request_id, presence: true
  # validates_uniqueness_of :sender_id, :scope => :recipient_id

  # Scope (prevents duplicate conversations between sender and recipient)
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

def index
  @users = User.all
  @conversations = Conversation.all

  respond_to do |format|
    format.html { }
    format.js {  }
  end

end

def create
  @request = Request.find(params[:request_id])
  if Conversation.between(params[:sender_id],params[:recipient_id]).where("request_id = ?", @request.id).present?
    @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).where("request_id = ?", @request.id).first
  else
    @conversation = Conversation.create!(conversation_params)
    @conversation.create_activity :create, owner: current_user, recipient: User.find(@conversation.recipient_id)
  end

  respond_to do |format|
    format.html { }
    format.js {  }
  end

  # redirect_to request_conversation_messages_path(@request, @conversation)
end

private
  def conversation_params
    params.permit(:sender_id, :recipient_id, :request_id)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div id="msg_form">

  <div class="ui segment">
    <% conversation.messages.each do |message| %>
      <% if message.body %>
        <% user = User.find(message.user_id) %>
          <div class="item">
            <div class="content">
              <div class="header"><strong><%= user.name %></strong>     <%= message.message_time %></div>
                <div class="list">
                  <div class="item">
                    <i class="right triangle icon"></i>
                      <%= message.body %>
                  </div>
                </div>
            </div>
          </div>
      <% end %>
    <% end %>
  </div>

  <%#= @request.inspect %>
  <%#= @conversation.inspect %>

  <%= form_for [conversation.messages.create], url: request_conversation_messages_path(@request, @conversation), html: {class: "ui reply form"}, remote: true do |f| %>
    <div class="field">
      <%= f.text_area :body, class: "form-control" %>
    </div>
      <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
    <div>
      <%= f.submit "Add Reply", class: "ui blue labeled submit icon button", id:"reply_btn" %>
    </div>
  <% end %>

</div>

app/views/conversations/create.js.erb
$('#responder_message_btn').html("<%= j render @conversation %>");

app/views/conversations/index.html.erb
<div class="ui segment">
  <h3>Mailbox</h3>
    <div class="ui list">
      <div class="item">
        <% @conversations.each do |conversation| %>
          <% if conversation.sender_id == current_user.id ||      conversation.recipient_id == current_user.id %>
            <% if conversation.sender_id == current_user.id %>
              <% recipient = User.find(conversation.recipient_id) %>
            <% else %>
              <% recipient = User.find(conversation.sender_id) %>
            <% end %>
            <%= link_to recipient.name,   conversation_messages_path(conversation)%>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

<div class="ui segment">
  <h3>All Users</h3>
    <div class="ui list">
      <% @users.each do |user| %>
        <% if user.id != current_user.id %>
          <div class="item">
            <%= user.name %> <%= link_to "Message me!", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post"%>
          </div>
        <% end %>
      <% end %>
    </div>
</div>