config/routes.rb
Rails.application.routes.draw do

  root "categories#index"

  resources :activities

  resources :password_resets

  resources :pages, only: [:show]

  resources :user_sessions

  resources :users do
    resources :requests
  end

  resources :experiences

  resources :ratings

  resources :requests do
    resources :conversations do
      resources :messages
    end
    resources :responses
  end

  resources :responses do
    resources :requests
  end

  resources :categories do
    resources :requests
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  # Tracking for Notifications (defaults to create, update, destroy)
  include PublicActivity::Common
  # tracked only: :update, owner: ->(controller, model) { controller && controller.current_user }

  # Sorcery authentication
  authenticates_with_sorcery!

  # ActiveRecord Relationships
  has_many :requests, :dependent => :delete_all
  has_one :experience, :dependent => :delete
  has_many :ratings, :dependent => :delete_all
  accepts_nested_attributes_for :experience
  accepts_nested_attributes_for :ratings
  has_many :responses, :dependent => :delete_all
  has_many :messages, :dependent => :delete_all
  has_many :conversations, :foreign_key => :sender_id, :dependent => :delete_all
  has_many :conversations, :foreign_key => :recipient_id, :dependent => :delete_all

  # ActiveRecord Validations
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }
  validates :email, uniqueness: true
  validates :name, presence: true
  validates :lastname, presence: true
  validates :points, presence: true
  validate :user_points_must_be_positive

  # Validation Methods
  def user_points_must_be_positive
    if self.points < 0
      errors.add(:points,": you don't have enough points for that.")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]
  # GET /users
  # GET /users.json

  # GET /users/1
  # GET /users/1.json
  def show
    @activities = PublicActivity::Activity.order("created_at desc").where("(owner_id = ? AND owner_type = ?) OR (recipient_id = ? AND recipient_type = ?)", current_user, "User", current_user, "User" ).page(params[:page])
    respond_to do |format|
      format.html { }
      format.js {  }
    end

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    unless @user.experience.present?
      @user.build_experience
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.points = 5

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path }
        format.json { render :root, status: :created, location: @user }
        auto_login(@user)
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        @user.create_activity :update, owner: current_user
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastname, :email, :password, :password_confirmation, experience_attributes:[:job, :education, :knowledge], rating_attributes:[:rating])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_delete.html.erb
  <div class="confirm_delete_msg">

    <h2>Are you sure you want to <br> permanently delete your account?</h2>

    <br>

    <%= button_to 'Delete', @user, method: :delete %>

      <br>
      
    <%= button_to 'Cancel', user_path, method: :get %>


  </div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Last Name" %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_signup.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/edit.html.erb
<div class="edit_user_form">

    <h2>Edit</h2>

    <br>

    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label "Last Name" %>
        <%= f.text_field :lastname %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>

        <br>
        <br>

      <%= f.fields_for :experience do |exp_form| %>

          <div class="field">
            <%= exp_form.label :education %>
            <%= exp_form.text_area :education %>
          </div>
          <div class="field">
            <%= exp_form.label :job %>
            <%= exp_form.text_area :job %>
          </div>
          <div class="field">
            <%= exp_form.label :knowledge %>
            <%= exp_form.text_area :knowledge %>
          </div>
      <% end %>
          <br>

      <div class="actions">
        <%= f.submit "Submit" %>
      </div>

    <% end %>
</div>

app/views/users/new.html.erb
<div class="create_page">

  <h1>New User</h1>

  <%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="user_account_page">

  <h1> MY ACCOUNT</h1>

  <div class="account_page_container">

    <div class="user_info_points_rating">

      <div class="user_info">
        <div class="name_contact">

            <p> <span>Name &emsp; &emsp; </span> <%= @user.name %> </p>

            <p> <span>Last-name &emsp; &emsp; </span> <%= @user.lastname %> </p>

            <p> <span>Email &emsp; &emsp; </span> <%= @user.email %> </p>

        </div>
          <br>
        <div class="user_experiences">
          <p>
            <h4>Education</h4>
            <% if @user.experience != nil %>
              <%= @user.experience.education %>
            <% end %>
          </p>
          <p>
            <h4>Job Experience</h4>
            <% if @user.experience != nil %>
              <%= @user.experience.job %>
            <% end %>
          </p>
          <p>
            <h4>Knowledge</h4>
            <% if @user.experience != nil %>
              <%= @user.experience.knowledge %>
            <% end %>
          </p>
          <br>

        <div class="edit_delete_user_btns">
          <button id="edit_user">
            <%= link_to 'Edit', edit_user_path(@user) %>
          </button>
          <button id="delete_account">
            <%= link_to 'Delete', user_url, remote: true %>
          </button>
          </div>
        </div>
      </div>

      <div class="user_account_points">
          <h3>Points</h3>
          <div id="points"><p><%= @user.points %></p></div>
      </div>

      <div class="user_account_rating">

          <h3>Rating</h3>
          <% if @user.ratings.average(:rating)== nil %>
            <h5> Participate in the community for a rating! </h5>
          <% else %>
            <%= '%.2f' % @user.ratings.average(:rating) %>/5 (<%= @user.ratings.count %> ratings total)
          <div class="notification_rating">
            <div class="star-ratings-css">
              <div class="star-ratings-css-top" style="width: <%= @user.ratings.average(:rating)/5.0*100.0 %>%">
                <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
              </div>
              <div class="star-ratings-css-bottom">
                <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
              </div>
            </div>
          </div>
          <% end %>
      </div>
    </div>

    <% if @activities.length > 0 %>
      <div class="user_account_notifications">

        <%= render "activities/notifications" %>

        <button id="clear_notifications">
          <%= link_to "Clear", activity_url, remote: true %>
        </button>

      </div>
    <% end %>
  </div>
</div>

app/views/users/show.js.erb
$('#delete_account').html("<%= j render 'delete' %>");