config/routes.rb
Rails.application.routes.draw do

  root "categories#index"

  resources :activities

  resources :password_resets

  resources :pages, only: [:show]

  resources :user_sessions

  resources :users do
    resources :requests
  end

  resources :experiences

  resources :ratings

  resources :requests do
    resources :conversations do
      resources :messages
    end
    resources :responses
  end

  resources :responses do
    resources :requests
  end

  resources :categories do
    resources :requests
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/request.rb
class Request < ActiveRecord::Base
  # Tracking for Notifications (defaults to create, update, destroy)
  include PublicActivity::Common
  # tracked owner: ->(controller, model) { controller && controller.current_user }

  # Callback for removing points from user during Request create
  before_create do
    self.active = true
    self.user.points = self.user.points - self.points
    self.user.save
  end

  # ActiveRecord Relationships
  belongs_to :user
  belongs_to :category
  has_many :responses
  has_many :conversations
  has_many :ratings

  # ActiveRecord Validations
  validates :category_id, :description, presence: true
  validates :points, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validate :expiration_date_limits

  # Valdiation methods
  def expiration_date_limits
    if self.expire == nil
      errors.add(:expire, "can't be left bank.")
    elsif self.expire < Date.today
      errors.add(:expire, "can't be in the past.")
    elsif self.expire > (Date.today + 30.days)
      errors.add(:expire, "can't be more than 30 days in the future.")
    end
  end

  # Method for request expiration using schedule.rb
  def self.expire_requests
    Request.all.each do |request|
      if request.active == true
        if request.expire <= Date.today
          request.active = false
          request.save
        end
      end
    end
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :update

  def index
    @user = current_user
    if @user.requests.where(active: true)
      @request = @user.requests.where(active: true).first
      @responders = User.joins(:responses).where(responses: {request_id: @request})
    end

    @inactive_requests = Request.where("user_id = ? AND active = ?", @user, false).order(created_at: :desc).page(params[:page])
    # @responders = User.joins(:responses).where(responses: {request_id: @active_request})
    # @requests = @active_requests + @inactive_requests
    # @requests = Request.all
    # for active it will always be the most recent date
    respond_to do |format|
      format.html { }
      format.js { }
    end
  end

  def show
    @request = Request.find(params[:id])
  end

  def new
    @user = current_user
    @request = Request.new
    @categories = Category.order("name")
  end

  def create
    @user = current_user
    @categories = Category.order("name")
    @request = Request.new(request_params)
    @request.user = current_user
    if @request.save
      redirect_to requests_path
    else
      render :new
    end
  end

  def edit
    @categories = Category.order("name")
  end

  def update
    # byebug
    @user = current_user
    @request = Request.find(params[:id])
    @request.active = params[:request][:active]
    @request.save
    @request.create_activity :update, owner: current_user
    @inactive_requests = Request.where("user_id = ? AND active = ?", @user, false).order(created_at: :desc).page(params[:page])
    # render js: "update"

    respond_to do |format|
      format.html { redirect_to :back }
      format.js {}
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to category_path
  end


private

  def request_params
    params.require(:request).permit(:description, :expire, :points, :active, :category_id)
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_active_request.html.erb
          <div class="active_request">
            <p>
              <strong>Category: &emsp; </strong> <%= @request.category.name %>
                <br>
              <strong>Description: &emsp; </strong> <%= @request.description %>
                <br>
              <strong>Points: &emsp; </strong> <%= @request.points %>
                <br>
              <strong>Expiry: &emsp; </strong> <%= @request.expire %>
            </p>
          </div>

          <h2>Responses</h2>

            <% @responders.each do |responder| %>
              <div class="responder_name_rating">

                <p><%= responder.name %> <%= responder.lastname %>
                    <% if responder.ratings.average(:rating) == nil %>
                      (Rating Pending)
                    <% else %>
                      <br> <span> Rating: <%= '%.2f' % responder.ratings.average(:rating) %>/5 </span>
                </p>
                    <div class="star_ratings">
                      <div class="star_ratings" style="width: <%= responder.ratings.average(:rating)/5.0*100.0 %>%">
                        <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                      </div>
                    </div>
                  <% end %>
                    <br>

                  <div id="responder_bio_form_btn">
                      <%= button_to 'Bio', requests_path, method: :get, remote: true %>
                  </div>

              </div>
            <% end %>

            <!-- <button id="done_request_btn"> <%#= link_to "Done", request_path(@active_request), remote: true %> </button> -->

app/views/requests/_bio.html.erb
  <div id="bio_form">

    <% @responders.each do |responder| %>
      <% if responder.experience != nil %>

        <p>
          <p>Education</p>
          <%= responder.experience.education %>
        </p>

        <p>
          <p>Job Experience</p>
          <%= responder.experience.job %>
        </p>

        <p>
          <p>Knowledge</p>
          <%= responder.experience.knowledge %>
        </p>

      <% else %>

        <p> Sorry! This user has not yet provided any extended bio information.</p>

      <% end %>
      </div>

        <div id="responder_message_btn">
          <%= button_to "Message me!",
          request_conversations_path(request_id: @request,
          sender_id: current_user.id,
          recipient_id: responder.id),
          method: "post", remote: true %>
        </div>

    <% end %>

app/views/requests/_create_request.html.erb
<button id="new_request"> <%= link_to "New Request", new_request_path %> </button>

app/views/requests/_messageboard.html.erb
<h1> Messages </h1>

app/views/requests/_newrequest.html.erb
<h1> New Request </h1>

  <div class="new_request_form">

    <%= form_for @request do |form| %>

      <div class="form_field">
        <%= form.label :description %>
        <%= form.text_area :description %>
      </div>

        <br>

      <div class="form_field">
        <%= form.label :expire %>
        <%= form.date :expire %>
      </div>

        <br>

      <div class="form_field">
        <%= form.label :points %>
        <%= form.number_field :points %>
      </div>

        <br>

      <div class="submit">
        <%= form.submit %>
      </div>

    <% end %>

app/views/requests/_rating.html.erb
<% responders = User.joins(:responses).where(responses: {request_id: Request.find(params[:id])}) %>

  <% if responders.length > 0 %>

    <div id="rating_form">

      <h3>Please select who helped you, and rate them accordingly</h3>

      <form action="/ratings" method="post">

        <% responders.each do |responder| %>
          <div class="responder_name_rating">
            <input name="rating[user_id]" id="user_id" type="radio" value="<%= responder.id %>" required>
              <%= responder.name %> <%= responder.lastname %>
            <% if responder.ratings.average(:rating) == nil %>
              <br> (Rating Pending)
            <% else %>
              <br> Rating: <%= '%.2f' % responder.ratings.average(:rating) %>/5
            <% end %>
              <br>
        <% end %>

        <div class="rating">
          <fieldset>
            <input type="hidden" name="rating[request_id]" value="<%= Request.find(params[:id]).id %>">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <input name="rating[rating]" id="e5" type="radio" value=5 required></a><label for="e5">★</label>
            <input name="rating[rating]" id="e4" type="radio" value=4></a><label for="e4">★</label>
            <input name="rating[rating]" id="e3" type="radio" value=3></a><label for="e3">★</label>
            <input name="rating[rating]" id="e2" type="radio" value=2></a><label for="e2">★</label>
            <input name="rating[rating]" id="e1" type="radio" value=1></a><label for="e1">★</label>
          </fieldset>
        </div>
          <input type="submit" value="Submit">
      </form>

    </div>

  <% else %>
    <div id="rating_form">
      <%= button_to 'Continue', requests_path, method: :get %>
    </div>
  <% end %>

app/views/requests/_request.html.erb
    <p>
    <span>Category: &emsp; </span> <%= request.category.name %> <br>

    <span>Description: &emsp; </span> <%= request.description %> <br>

    <span>Points: &emsp; </span> <%= request.points %> <br>
    </p>
    <br>

app/views/requests/index.html.erb
<div class="user_requests_page">

    <h1>MY REQUESTS</h1>

    <div class="requests_page_container">

      <div class="user_active_request">

        <% if @user.requests.where("active = ?", true).exists? %>

          <h2> My Request </h2>
          <br>
          <div class="done_btn">
            <%= form_for [@user, @request], remote: true do |f| %>
            <%= f.hidden_field :active, value: false, method: :patch %>
            <%= f.submit "Clear Request" %>
          <% end %>
        </div>

          <%= render "active_request", object: @request %>

        <% else %>

        <div class="new_request_btn">  <%= render 'create_request' %> </div>

        <% end %>

      </div>


      <div class="old_requests">

        <h2> Old Requests </h2>

          <br>
            <div class="old_requests_container">
              <div class="inactive_requests">
                <% if @inactive_requests.present? %>
                  <%= render @inactive_requests %>
                  <%= paginate @inactive_requests %>
                  <% end %>
              </div>
            </div>
      </div>
    </div>
</div>

app/views/requests/index.js.erb
$('#responder_bio_form_btn').html("<%= j render 'bio', object: @responder %>");

app/views/requests/new.html.erb
<div class="new_request_page">

    <div class="new_request_form">

      <h2> New Request </h2>

      <br>

      <%= form_for @request, url: {action: "create"} do |form| %>

        <% if @request.errors.any? %>
          <div id="error_explanation">
            <h4><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h4>

            <ul>
              <% @request.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>

          </div>
        <% end %>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h4><%= pluralize(@user.errors.count, "error") %> prohibited this request from being saved:</h4>

            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>

          </div>
        <% end %>

        <div class="form_field">
          <%= form.label :Category %>
          <%= form.collection_select :category_id, @categories, :id, :name, include_blank: true, :prompt => "Choose a Category" %>
        </div>

          <br>

        <div class="form_field">
          <%= form.label :description %>
          <%= form.text_area :description, placeholder: "How would you describe your question?" %>
        </div>

          <br>

        <div class="form_field">
          <%= form.label :expire %>
          <%= form.date_field :expire, :value => (Date.today + 7.days).strftime("%Y-%m-%d") %>
        </div>

          <br>

        <div class="form_field">
          <%= form.label :points %>
          <%= form.number_field :points, placeholder: "How many points would you like to offer?" %>
        </div>

          <br>

        <div class="submit">
          <%= form.submit "Submit" %>
        </div>

      <% end %>

    </div>
  </div>

app/views/requests/update.js.erb
$(".old_requests_container").html('<%= j render @inactive_requests %>');
// $(".user_active_request").html("<%= j render 'create_request' %>");
$(".user_active_request").html("<%= j render 'rating' %>");