config/routes.rb
Rails.application.routes.draw do

  root "categories#index"

  resources :activities

  resources :password_resets

  resources :pages, only: [:show]

  resources :user_sessions

  resources :users do
    resources :requests
  end

  resources :experiences

  resources :ratings

  resources :requests do
    resources :conversations do
      resources :messages
    end
    resources :responses
  end

  resources :responses do
    resources :requests
  end

  resources :categories do
    resources :requests
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :requests

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
skip_before_action :require_login, only: [:index]

  def index
    @user = User.new
    @categories = Category.all.order('name ASC')
  end

  def show
    @category = Category.find(params[:id])
    @requests = @category.requests.where(active: true).page(params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new
    @category.save
    redirect_to root_path
  end

  def edit
    # not in use
  end

  def update
    # not in use
  end

  def destroy
    # not in use
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_about.html.erb
<h1> About Cloudfiller </h1>

  <p>
    We live in an age where we can Google almost anything.
    But sometimes there are questions Google just can't answer
    easily, and we want to find someone to ask. What if there's
    nobody in our social circle who can answer the question?

    That's where Cloudfiller comes in: bridging gaps
    and connecting communities.
  </p>

app/views/categories/index.html.erb
<div class="category_list_page">

<h1>CATEGORIES</h1>

  <div class="categories">
    <ul id="category_list">
        <% @categories.each do |category| %>
      <li>
         <%= link_to category.name.upcase, category_path(category)%>
      </li>
        <% end %>
    </ul>
  </div>
</div>

app/views/categories/show.html.erb
<div class="category_requests_show_page">

  <h1><%= @category.name.upcase %> REQUESTS </h1>

    <% if flash[:notice] %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <div class="category_requests_container">
      <div class="page_entries">
        <h4><%= page_entries_info @requests %></h4>
          <% if Request.joins(:responses).where(responses: {user_id: current_user}, requests: {active: true}).length >= 3 %>
          <h4>Oops! You already have 3 active responses. You need to complete one before adding another.</h4>
          <% end %>
      </div>
        <ul>
            <% @requests.each do |request| %>
              <div class="category_active_request">
                <li>
                    <p>
                    <strong>Description: &emsp; </strong> <%= request.description %>
                      <br>
                    <strong>Points: &emsp; </strong> <%= request.points %>
                      <br>
                    <strong>Request Expires: &emsp; </strong> <%= request.expire %>
                  </p>

                  <div id="request_response_<%= request.id %>">
                    <%= render "/responses/request_response", request: request %>
                  </div>

                    <% if request.user == current_user %>
                    <% elsif Request.joins(:responses).where(responses: { user_id: current_user }, requests: { active: true }).length >= 3 %>
                    <% elsif Request.joins(:responses).where(responses: { user_id: current_user }, requests: { id: request }).exists? %>
                    <% else %>
                      <button id="respond_to_request_<%= request.id %>">
                          <%= link_to "Respond",
                                      "/requests/#{request.id}/responses",
                                      method: :post,
                                      remote: true %>
                      </button>
                    <% end %>
                </li>
              </div>
            <% end %>
        </ul>
          <%= paginate @requests %>
    </div>
</div>